server:
  port: 8089

spring:
  application:
    name: operis-project-service
  cloud:
    config:
      fail-fast: true
      # Configuration de la stratégie de retry pour la connexion au Config Server
      retry:
        initial-interval: 3000
        max-interval: 10000
        max-attempts: 10
        multiplier: 1.5
      discovery:
        enabled: false
  config:
    # On donne l'URL directe dans le réseau Docker
    import: "optional:configserver:http://operis-config:8888"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://operis-discovery:8761/eureka/}