services:
  projectdb:
    image: mysql:latest
    container_name: projectdb
    ports:
      - "4444:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis_project
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - operis-network

# Service pour le serveur de découverte Eureka
  operis-discovery:
    build:
      context: . # Racine du projet
      dockerfile: operis-discovery/Dockerfile
    container_name: operis-discovery
    ports:
      - "8761:8761"
    networks:
      - operis-network

# Service pour l'application operis-project
  operis-project-service:
    build:
      context: . # Racine du projet
      dockerfile: operis-project/operis-project-service/Dockerfile
    container_name: operis-project-service
    ports:
      - "8089:8089"
    depends_on:
      - projectdb
      - operis-discovery
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://projectdb:3306/operis_project?serverTimezone=UTC
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://operis-discovery:8761/eureka/
    networks:
      - operis-network

# operis-gateway service
  operis-gateway:
    build:
      context: . # On reste à la racine pour que Docker accède au dossier du module
      dockerfile: operis-gateway/Dockerfile
    container_name: operis-gateway
    ports:
      - "8080:8080"
    depends_on:
      - operis-discovery
      - operis-project-service
    environment:
      # URL pour qu'elle puisse contacter Eureka dans le réseau Docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://operis-discovery:8761/eureka/
    networks:
      - operis-network

networks:
  operis-network:
    driver: bridge

volumes:
  mysql_data: