server:
  port: 8080

spring:
  application:
    name: operis-gateway
  config:
    import: "optional:configserver:http://operis-config:8888"

  cloud:
    gateway:
      routes:
        - id: operis-project-service
          uri: lb://operis-project-service
          predicates:
            - Path=/api/projects/**
          filters:
            - AddRequestHeader=X-Request-Source, Gateway
    config:
      discovery:
        enabled: true
        service-id: operis-config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: false
    fetch-registry: true