# Le nom unique de ce service dans ton réseau.
spring:
  application:
    name: operis-discovery

  # Le port standard pour Eureka.
server:
  port: 8761

eureka:
  client:
    # C'est LUI le serveur, il n'a pas besoin de s'enregistrer
    # auprès de lui-même (sinon il bouclerait à l'infini).
    register-with-eureka: false

    # Il n'a pas besoin de télécharger la liste des services
    # depuis un autre serveur (puisque c'est lui qui détient la liste).
    fetch-registry: false
    server:
        # Désactive le mode survie qui cause l'alerte
        enable-self-preservation: false
        # Fréquence à laquelle Eureka nettoie les services morts (10 secondes)
        eviction-interval-timer-in-ms: 10000